// Query-based waveform engine.
//
// This module cuts the deep seam described in
// .trellis/tasks/05-08-goa-timing-simulator-design/engine-rewrite-plan.md:
// instead of the UI pulling the full 120-frame SignalTrace.segments/edges,
// it asks this engine "what do I draw in this window", "which edge is nearest
// this mouse position", and "summarize this signal over this range".
//
// render.ts consumes this through the worker for 120-frame waveform views.
// All GOA semantics (by-line carry, by-frame period, combin, mask, TER/CPV2)
// are reused from simulator.ts — nothing is reimplemented here.
//
// Known limitations:
//  1. CK / LS signals come from the one-frame simulateProject preview and are
//     repeated per frame for long-window queries.
//  2. GPO windows use a period anchor (repeatCount+1, plus mask frame period)
//     so overview/nearest-edge queries do not generate all 120 frames. If a
//     long-repeat period costs more than the requested window, it falls back
//     to the old from-0 path.
//  3. Overview pixel-bin is the simplified version: a pixel column with any
//     high segment becomes level 1. Pulse-count annotations are deferred to
//     Phase 3.
import { simulateGpoOutWindow, simulateGpoWindow, simulateProject } from './simulator';
import { absPcnt } from './time';
import type { DraftProject, Edge, GpoConfig, LogicLevel, Segment, SignalFamily, SignalTrace, SimulationResult, TimingBase } from './types';

export type QueryMode = 'exact' | 'overview';

export type SignalQuery = {
  signalIds: string[];
  startPcnt: number;
  endPcnt: number;
  pixelWidth: number;
  mode: QueryMode;
};

export type DrawableSegment = {
  signalId: string;
  start: number;
  end: number;
  level: 0 | 1;
};

export type EdgeQuery = {
  signalId: string;
  at: number;
  radiusPcnt: number;
};

export type SignalSummary = {
  signalId: string;
  pulseCount: number;
  firstWidthSeconds?: number;
  periodSeconds?: number;
};

export type WaveformEngine = {
  querySignals(query: SignalQuery): DrawableSegment[];
  nearestEdge(query: EdgeQuery): Edge | undefined;
  summarizeSignal(signalId: string, startPcnt: number, endPcnt: number): SignalSummary;
  queryableSignalIds(): string[];
};

// A resolver turns a signalId + frame window into raw segments over
// [0, frameWindow * frameTotal). Cropping to the query window happens after.
type GpoResolver = {
  kind: 'gpo';
  gpoIndex: number;
  useOut: boolean; // true -> simulateGpoOutWindow (combin merge), false -> simulateGpoWindow (raw)
};
type CachedResolver = {
  kind: 'cached';
  trace: SignalTrace; // CK / LS / MT9603 driver_tp — generated by simulateProject, full-frame, cropped on query
  repeatFrame: boolean;
};
type Resolver = GpoResolver | CachedResolver | undefined;
type PeriodBase = {
  segments: Segment[];
  cycleStart: number;
  cycleTotal: number;
  frameWindow: number;
};

export function createWaveformEngine(project: DraftProject): WaveformEngine {
  if (!project.timing) throw new Error('Timing base is missing. Import XLSX first.');
  const timing = project.timing;
  const frameTotal = timing.pcntPerLine * timing.vtotal;
  const sim: SimulationResult = simulateProject(project);
  const gposByIndex = new Map<number, GpoConfig>(project.gpos.map((g) => [g.index, g]));
  const segmentCache = new Map<string, Segment[]>();
  const periodCache = new Map<string, PeriodBase | undefined>();

  // Build signalId -> resolver. Only the output namespace from simulateProject
  // is exposed (family:*, gpo:${idx}:*, rst:manual, ter:manual, ck*, ls:*,
  // driver_tp:*). The intermediate gpo${idx}:raw/merge ids are NOT exposed.
  const resolvers = new Map<string, Resolver>();
  const namesById = new Map<string, string>();

  for (const family of sim.families) registerFamily(family, resolvers, namesById);
  for (const gpo of project.gpos) {
    register(`gpo:${gpo.index}:raw`, { kind: 'gpo', gpoIndex: gpo.index, useOut: false }, gpoLabel(gpo, 'raw'));
    register(`gpo:${gpo.index}:merge`, { kind: 'gpo', gpoIndex: gpo.index, useOut: true }, gpoLabel(gpo, 'out'));
  }
  if (project.rstGpo !== undefined) {
    const gpo = gposByIndex.get(project.rstGpo);
    if (gpo) register('rst:manual', { kind: 'gpo', gpoIndex: gpo.index, useOut: true }, 'RST out');
  }
  // CK / LS / MT9603 driver_tp come from the cached full-frame sim result.
  for (const trace of [...sim.signals, ...sim.gpoSignals]) {
    if (resolvers.has(trace.id)) continue;
    register(trace.id, { kind: 'cached', trace, repeatFrame: trace.kind === 'ck' || trace.id.startsWith('ls:') }, trace.name);
  }

  function register(id: string, resolver: Resolver, name: string): void {
    if (!resolvers.has(id)) {
      resolvers.set(id, resolver);
      namesById.set(id, name);
    }
  }

  function registerFamily(family: SignalFamily, map: Map<string, Resolver>, names: Map<string, string>): void {
    if (family.rawGpo !== undefined) {
      register(`${family.id}:raw`, { kind: 'gpo', gpoIndex: family.rawGpo, useOut: false }, `${family.label} raw`);
      if (family.sourceGpo !== undefined) {
        register(`${family.id}:source`, { kind: 'gpo', gpoIndex: family.sourceGpo, useOut: false }, `${family.label} merge`);
      }
      register(`${family.id}:merge`, { kind: 'gpo', gpoIndex: family.rawGpo, useOut: true }, `${family.label} out`);
    }
  }

  function resolveSegments(signalId: string, frameWindow: number): Segment[] {
    const cacheKey = `${signalId}:${frameWindow}`;
    const cached = segmentCache.get(cacheKey);
    if (cached) return cached;
    const resolver = resolvers.get(signalId);
    if (!resolver) return [];
    if (resolver.kind === 'cached') return resolver.repeatFrame && frameWindow > 1
      ? repeatPeriodSegments(resolver.trace.segments, 0, frameWindow * frameTotal, 0, frameTotal)
      : resolver.trace.segments;
    const gpo = gposByIndex.get(resolver.gpoIndex);
    if (!gpo) return [];
    const segments = resolver.useOut
      ? simulateGpoOutWindow(gpo, project.gpos, timing, false, frameWindow)
      : simulateGpoWindow(gpo, timing, false, frameWindow);
    segmentCache.set(cacheKey, segments);
    return segments;
  }

  function resolveWindowSegments(signalId: string, start: number, end: number): Segment[] {
    const resolver = resolvers.get(signalId);
    if (!resolver) return [];
    if (resolver.kind === 'cached') {
      return resolver.repeatFrame ? repeatPeriodSegments(resolver.trace.segments, start, end, 0, frameTotal) : cropSegments(resolver.trace.segments, start, end);
    }

    const fullFrameWindow = Math.max(1, Math.ceil(end / frameTotal));
    const steadyFrame = steadyFrameSegments(signalId, resolver, start, end);
    if (steadyFrame) return steadyFrame;
    const spec = periodSpecFor(resolver);
    const periodFrameWindow = spec ? Math.max(1, Math.ceil((spec.cycleStart + spec.cycleTotal) / frameTotal)) : Infinity;
    // If the period anchor costs more than the requested window, keep the old
    // path. Equal cost is okay because the period cache helps repeated queries.
    if (!spec || periodFrameWindow > fullFrameWindow) return cropSegments(resolveSegments(signalId, fullFrameWindow), start, end);
    const period = periodBaseFor(signalId, resolver, spec, periodFrameWindow);
    if (!period) return cropSegments(resolveSegments(signalId, fullFrameWindow), start, end);
    return repeatPeriodSegments(period.segments, start, end, period.cycleStart, period.cycleTotal);
  }

  function steadyFrameSegments(signalId: string, resolver: GpoResolver, start: number, end: number): Segment[] | undefined {
    if (start < frameTotal || end <= start) return undefined;
    const frame = Math.floor(start / frameTotal);
    if (Math.floor((end - 1) / frameTotal) !== frame) return undefined;
    const transient = transientPcntFor(resolver);
    const frameStart = frame * frameTotal;
    const relStart = start - frameStart;
    const relEnd = end - frameStart;
    if (transient <= 0 || relStart < transient || relEnd > frameTotal) return undefined;
    return cropSegments(resolveSegments(signalId, 1), relStart, relEnd)
      .map((s) => ({ ...s, start: s.start + frameStart, end: s.end + frameStart }));
  }

  function periodBaseFor(signalId: string, resolver: GpoResolver, spec?: { cycleStart: number; cycleTotal: number }, specFrameWindow?: number): PeriodBase | undefined {
    if (periodCache.has(signalId)) return periodCache.get(signalId);
    const period = spec ?? periodSpecFor(resolver);
    const gpo = gposByIndex.get(resolver.gpoIndex);
    if (!period || !gpo) {
      periodCache.set(signalId, undefined);
      return undefined;
    }
    const frameWindow = specFrameWindow ?? Math.max(1, Math.ceil((period.cycleStart + period.cycleTotal) / frameTotal));
    const base = resolver.useOut
      ? simulateGpoOutWindow(gpo, project.gpos, timing, false, frameWindow)
      : simulateGpoWindow(gpo, timing, false, frameWindow);
    const out = { segments: base, cycleStart: period.cycleStart, cycleTotal: period.cycleTotal, frameWindow };
    periodCache.set(signalId, out);
    return out;
  }

  function periodSpecFor(resolver: GpoResolver): { cycleStart: number; cycleTotal: number } | undefined {
    const gpo = gposByIndex.get(resolver.gpoIndex);
    if (!gpo) return undefined;
    let cycleLines = cycleLinesForGpo(gpo, timing);
    let needsSteadyAnchor = byLineHasTransient(gpo, timing);

    if (resolver.useOut) {
      const other = project.gpos.find((item) => item.index === gpo.combinSel);
      if (other && ![0, 4, 5, 6].includes(gpo.combinType)) {
        cycleLines = lcm(cycleLines, cycleLinesForGpo(other, timing));
        needsSteadyAnchor ||= byLineHasTransient(other, timing);
      }
    }

    const cycleTotal = cycleLines * timing.pcntPerLine;
    return {
      cycleStart: needsSteadyAnchor ? cycleTotal : 0,
      cycleTotal,
    };
  }

  function transientPcntFor(resolver: GpoResolver): number {
    const gpo = gposByIndex.get(resolver.gpoIndex);
    if (!gpo) return 0;
    let out = byLineHasTransient(gpo, timing) ? Math.max(1, gpo.repeatCount + 1) * timing.pcntPerLine : 0;
    if (resolver.useOut) {
      const other = project.gpos.find((item) => item.index === gpo.combinSel);
      if (other && ![0, 4, 5, 6].includes(gpo.combinType) && byLineHasTransient(other, timing)) {
        out = Math.max(out, Math.max(1, other.repeatCount + 1) * timing.pcntPerLine);
      }
    }
    return out;
  }

  function gpoForSignal(signalId: string): GpoConfig | undefined {
    const resolver = resolvers.get(signalId);
    if (resolver?.kind === 'gpo') return gposByIndex.get(resolver.gpoIndex);
    return undefined;
  }

  function nameForSignal(signalId: string): string {
    return namesById.get(signalId) ?? signalId;
  }

  return {
    querySignals(query: SignalQuery): DrawableSegment[] {
      const out: DrawableSegment[] = [];
      for (const signalId of query.signalIds) {
        const segments = querySegmentsForSignal(signalId, query);
        for (const s of segments) out.push({ signalId, start: s.start, end: s.end, level: s.level });
      }
      return out;
    },

    nearestEdge(query: EdgeQuery): Edge | undefined {
      // Generate only a small window around `at` — avoids the full edge list.
      const radius = Math.max(1, query.radiusPcnt);
      const start = Math.max(0, query.at - radius);
      const end = query.at + radius;
      const cropped = resolveWindowSegments(query.signalId, start, end);
      if (cropped.length === 0) return undefined;
      const gpo = gpoForSignal(query.signalId);
      // Derive edges within the window, seeding prevLevel with the real level at
      // the window start (from the un-cropped stream) so a crop boundary is not
      // mistaken for a rising/falling edge. extractEdges assumes segments start
      // at pcnt 0 with prevLevel 0, which is wrong for an arbitrary sub-window.
      const levelAtStart = levelAtPcnt(cropped, start);
      const edges = edgesInWindow(query.signalId, nameForSignal(query.signalId), cropped, levelAtStart, gpo?.index);
      let best: Edge | undefined;
      let bestDist = Infinity;
      for (const edge of edges) {
        const dist = Math.abs(edge.at - query.at);
        if (dist < bestDist && dist <= radius) {
          bestDist = dist;
          best = edge;
        }
      }
      return best;
    },

    summarizeSignal(signalId: string, startPcnt: number, endPcnt: number): SignalSummary {
      const gpo = gpoForSignal(signalId);
      // by-frame: derive W/T from gpo.entries + timing — window-agnostic (mirrors
      // render.ts pulseSummary by-frame branch).
      if (gpo?.repeatMode === 1) return summarizeByFrame(signalId, gpo, timing, frameTotal);
      const resolver = resolvers.get(signalId);
      if (resolver?.kind === 'cached' && resolver.repeatFrame) return summarizeFromSegments(signalId, resolver.trace.segments, timing);
      // generic: first high-pulse width + first period from windowed segments.
      const cropped = resolveWindowSegments(signalId, startPcnt, endPcnt);
      return summarizeFromSegments(signalId, cropped, timing);
    },

    queryableSignalIds(): string[] {
      return [...resolvers.keys()].sort();
    },
  };

  function querySegmentsForSignal(signalId: string, query: SignalQuery): Segment[] {
    if (query.mode === 'overview') {
      const resolver = resolvers.get(signalId);
      if (resolver?.kind === 'cached' && resolver.repeatFrame) {
        return overviewBinPeriodic(resolver.trace.segments, query.startPcnt, query.endPcnt, query.pixelWidth, 0, frameTotal);
      }
      if (resolver?.kind === 'gpo') {
        const fullFrameWindow = Math.max(1, Math.ceil(query.endPcnt / frameTotal));
        const spec = periodSpecFor(resolver);
        const periodFrameWindow = spec ? Math.max(1, Math.ceil((spec.cycleStart + spec.cycleTotal) / frameTotal)) : Infinity;
        const period = spec && periodFrameWindow < fullFrameWindow ? periodBaseFor(signalId, resolver, spec, periodFrameWindow) : undefined;
        if (period && period.frameWindow < fullFrameWindow) {
          return overviewBinPeriodic(period.segments, query.startPcnt, query.endPcnt, query.pixelWidth, period.cycleStart, period.cycleTotal);
        }
      }
    }
    const cropped = resolveWindowSegments(signalId, query.startPcnt, query.endPcnt);
    if (query.mode === 'exact' || cropped.length <= query.pixelWidth) return cropped;
    return overviewBin(cropped, query.startPcnt, query.endPcnt, query.pixelWidth);
  }
}

function cycleLinesForGpo(gpo: GpoConfig, timing: TimingBase): number {
  if (gpo.repeatMode === 1) return Math.max(1, gpo.repeatCount + 1) * timing.vtotal;
  const periodLines = Math.max(1, gpo.repeatCount + 1);
  return gpo.maskEnabled ? lcm(periodLines, timing.vtotal) : periodLines;
}

function byLineHasTransient(gpo: GpoConfig, timing: TimingBase): boolean {
  if (gpo.repeatMode !== 0) return false;
  const periodLines = Math.max(1, gpo.repeatCount + 1);
  const entries = gpo.entries
    .filter((e) => e.enabled && e.lcnt >= 0 && e.lcnt < periodLines && e.pcnt >= 0 && e.pcnt < timing.pcntPerLine)
    .sort((a, b) => a.lcnt - b.lcnt || a.pcnt - b.pcnt || a.index - b.index);
  const last = entries[entries.length - 1];
  return last?.level === 1;
}

function gcd(a: number, b: number): number {
  let x = Math.abs(Math.trunc(a));
  let y = Math.abs(Math.trunc(b));
  while (y) [x, y] = [y, x % y];
  return Math.max(1, x);
}

function lcm(a: number, b: number): number {
  return Math.max(1, Math.trunc(a / gcd(a, b) * b));
}

function gpoLabel(gpo: GpoConfig, suffix: string): string {
  return `${gpo.group.replace(/^GPO\d+_?/i, '') || gpo.group} ${suffix}`;
}

function cropSegments(segments: Segment[], start: number, end: number): Segment[] {
  const out: Segment[] = [];
  for (const s of segments) {
    if (s.end <= start || s.start >= end) continue;
    out.push({
      start: Math.max(s.start, start),
      end: Math.min(s.end, end),
      level: s.level,
      source: s.source,
    });
  }
  return out;
}

function repeatPeriodSegments(segments: Segment[], start: number, end: number, cycleStart: number, cycleTotal: number): Segment[] {
  if (end <= start || cycleTotal <= 0) return [];
  const out: Segment[] = [];
  if (start < cycleStart) {
    out.push(...cropSegments(segments, start, Math.min(end, cycleStart)));
  }
  if (end <= cycleStart) return out;

  const cycle = cropSegments(segments, cycleStart, cycleStart + cycleTotal)
    .map((s) => ({ ...s, start: s.start - cycleStart, end: s.end - cycleStart }));
  let pos = Math.max(start, cycleStart);
  while (pos < end) {
    const offset = (pos - cycleStart) % cycleTotal;
    const take = Math.min(end - pos, cycleTotal - offset);
    for (const s of cycle) {
      if (s.end <= offset || s.start >= offset + take) continue;
      out.push({
        start: pos + Math.max(s.start, offset) - offset,
        end: pos + Math.min(s.end, offset + take) - offset,
        level: s.level,
        source: s.source,
      });
    }
    pos += take;
  }
  return out;
}

// Real level at an absolute pcnt, walking the un-cropped stream. Returns 0
// before the first segment (matches simulator's implicit low start).
function levelAtPcnt(segments: Segment[], at: number): LogicLevel {
  for (const s of segments) {
    if (at >= s.start && at < s.end) return s.level;
    if (s.start > at) break;
  }
  return 0;
}

// Like simulator.extractEdges but seeds prevLevel with the real level at the
// window start, so a crop boundary (where a segment was clamped to `start`)
// is not reported as a spurious edge. Only edges strictly inside (start, end]
// are emitted.
function edgesInWindow(signalId: string, signalName: string, segments: Segment[], prevLevel: LogicLevel, gpoIndex?: number): Edge[] {
  const edges: Edge[] = [];
  let prev = prevLevel;
  for (const segment of segments) {
    if (segment.level !== prev) {
      edges.push({
        id: `${signalId}@${segment.start}:${segment.level}`,
        signalId,
        signalName,
        at: segment.start,
        edge: segment.level ? 'rising' : 'falling',
        level: segment.level,
        source: segment.source,
        gpoIndex,
      });
    }
    prev = segment.level;
  }
  return edges;
}

// Simplified overview: collapse to one segment per pixel column. A column is
// high if any segment overlapping it is high. Adjacent same-level columns
// merge. O(segments).
function overviewBin(segments: Segment[], startPcnt: number, endPcnt: number, pixelWidth: number): Segment[] {
  const span = Math.max(1, endPcnt - startPcnt);
  const pcntPerPx = span / Math.max(1, pixelWidth);
  const columns = new Uint8Array(pixelWidth); // 0 low, 1 high
  for (const s of segments) {
    if (s.level !== 1) continue;
    const fromPx = Math.max(0, Math.floor((s.start - startPcnt) / pcntPerPx));
    const toPx = Math.min(pixelWidth - 1, Math.floor((s.end - startPcnt - 1) / pcntPerPx));
    for (let px = fromPx; px <= toPx; px += 1) columns[px] = 1;
  }
  const out: Segment[] = [];
  let level: 0 | 1 = (columns[0] ?? 0) as 0 | 1;
  let segStart = startPcnt;
  for (let px = 1; px < pixelWidth; px += 1) {
    const col = (columns[px] ?? 0) as 0 | 1;
    if (col !== level) {
      out.push({ start: segStart, end: startPcnt + px * pcntPerPx, level, source: 'overview' });
      segStart = startPcnt + px * pcntPerPx;
      level = col;
    }
  }
  out.push({ start: segStart, end: endPcnt, level, source: 'overview' });
  return out.filter((s) => s.end > s.start);
}

function overviewBinPeriodic(segments: Segment[], startPcnt: number, endPcnt: number, pixelWidth: number, cycleStart: number, cycleTotal: number): Segment[] {
  const span = Math.max(1, endPcnt - startPcnt);
  const pcntPerPx = span / Math.max(1, pixelWidth);
  const columns = new Uint8Array(pixelWidth);
  const markHigh = (start: number, end: number) => {
    if (end <= start) return;
    const fromPx = Math.max(0, Math.floor((start - startPcnt) / pcntPerPx));
    const toPx = Math.min(pixelWidth - 1, Math.floor((end - startPcnt - 1) / pcntPerPx));
    for (let px = fromPx; px <= toPx; px += 1) columns[px] = 1;
  };

  for (const s of cropSegments(segments, startPcnt, Math.min(endPcnt, cycleStart))) {
    if (s.level === 1) markHigh(s.start, s.end);
  }

  const cycle = cropSegments(segments, cycleStart, cycleStart + cycleTotal)
    .filter((s) => s.level === 1)
    .map((s) => ({ start: s.start - cycleStart, end: s.end - cycleStart }));
  let pos = Math.max(startPcnt, cycleStart);
  while (pos < endPcnt) {
    const offset = (pos - cycleStart) % cycleTotal;
    const take = Math.min(endPcnt - pos, cycleTotal - offset);
    for (const s of cycle) {
      if (s.end <= offset || s.start >= offset + take) continue;
      markHigh(pos + Math.max(s.start, offset) - offset, pos + Math.min(s.end, offset + take) - offset);
    }
    pos += take;
  }

  const out: Segment[] = [];
  let level: 0 | 1 = (columns[0] ?? 0) as 0 | 1;
  let segStart = startPcnt;
  for (let px = 1; px < pixelWidth; px += 1) {
    const col = (columns[px] ?? 0) as 0 | 1;
    if (col !== level) {
      out.push({ start: segStart, end: startPcnt + px * pcntPerPx, level, source: 'overview' });
      segStart = startPcnt + px * pcntPerPx;
      level = col;
    }
  }
  out.push({ start: segStart, end: endPcnt, level, source: 'overview' });
  return out.filter((s) => s.end > s.start);
}

function summarizeByFrame(signalId: string, gpo: GpoConfig, timing: TimingBase, frameTotal: number): SignalSummary {
  const periodFrames = Math.max(1, gpo.repeatCount + 1);
  const periodTotal = periodFrames * frameTotal;
  const events = gpo.entries
    .filter((e) => e.enabled)
    .map((e) => ({ at: e.frameCount * frameTotal + absPcnt(e.lcnt, e.pcnt, timing.pcntPerLine), level: e.level }))
    .filter((e) => e.at >= 0 && e.at < periodTotal)
    .sort((a, b) => a.at - b.at);
  if (events.length === 0) return { signalId, pulseCount: 0 };
  // Mirrors render.ts pulseSummary by-frame branch: rising = level 1 whose
  // circular predecessor is level 0.
  const len = events.length;
  let rising: { at: number; level: 0 | 1 } | undefined;
  for (let i = 0; i < len; i += 1) {
    const prev = events[(i + len - 1) % len];
    if (events[i].level === 1 && prev.level === 0) { rising = events[i]; break; }
  }
  if (!rising) return { signalId, pulseCount: events.filter((e) => e.level === 1).length };
  const falling = events.find((e) => e.level === 0 && e.at > rising.at) ?? events.find((e) => e.level === 0);
  const widthPcnt = falling ? (falling.at > rising.at ? falling.at - rising.at : periodTotal - rising.at + falling.at) : periodTotal;
  return {
    signalId,
    pulseCount: events.filter((e) => e.level === 1).length,
    firstWidthSeconds: widthPcnt * timing.pcntSeconds,
    periodSeconds: periodTotal * timing.pcntSeconds,
  };
}

function summarizeFromSegments(signalId: string, segments: Segment[], timing: TimingBase): SignalSummary {
  const highs = segments.filter((s) => s.level === 1);
  if (highs.length === 0) return { signalId, pulseCount: 0 };
  const firstWidthSeconds = (highs[0].end - highs[0].start) * timing.pcntSeconds;
  const periodSeconds = highs.length > 1 ? (highs[1].start - highs[0].start) * timing.pcntSeconds : undefined;
  return { signalId, pulseCount: highs.length, firstWidthSeconds, periodSeconds };
}
